name: Quiet Hours Cron Job

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call the cron job endpoint
        run: |
          curl --request GET \
          --url '${{ secrets.DEPLOYMENT_URL }}' \
          --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'